# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Nvidia.GeForceGameReadyDriver
PackageVersion: "536.40"
PackageLocale: en-US
Publisher: NVIDIA Corporation
PublisherUrl: https://www.nvidia.com/en-us/
PublisherSupportUrl: https://www.nvidia.com/en-us/support/
PrivacyUrl: https://www.nvidia.com/en-us/about-nvidia/privacy-policy/
PackageName: NVIDIA Graphics Driver
License: Proprietary
LicenseUrl: https://www.nvidia.com/en-us/drivers/nvidia-license/
Copyright: Copyright © 2011-2021 NVIDIA Corporation # From installer metadata
ShortDescription: NVIDIA Game Ready drivers for GeForce-series cards ('Maxwell' and newer)
ManifestType: defaultLocale
ManifestVersion: 1.4.0
