# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Nvidia.GeForceGameReadyDriver
PackageVersion: "536.23"
Installers:
- InstallerUrl: https://us.download.nvidia.com/Windows/536.23/536.23-desktop-win10-win11-64bit-international-dch-whql.exe
  Architecture: x64
  MinimumOSVersion: 10.0.0.0
  InstallerType: exe
  InstallerSha256: 97F29F85425F5D35C6191573F5EF5AE1E38C7750E0E6CE21D1727CFDA8010CA8
  InstallerSwitches:
    Silent: /s
    SilentWithProgress: /s
    Custom: /gfexperienceinitiated /noreboot # Prevent GeForce Experience installation; no reboot
  ExpectedReturnCodes:
    - InstallerReturnCode: 3858759936
      ReturnResponse: systemNotSupported
  Scope: machine
ManifestType: installer
ManifestVersion: 1.4.0
